name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy_develop:
        timeout-minutes: 10
        name: NPM Publish
        runs-on: ubuntu-latest
        environment: npm
        steps:
            - uses: actions/checkout@v3
              with:
                  lfs: true
            - run: |
                  npm ci
            - id: publish
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  greater-version-only: true
            - if: steps.publish.outputs.type != 'none'
              run: |
                  echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
